spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: saK095450646
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable : true
            required : true
          from: contact@email.com
      from:
        name: Sak

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/rithysak
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8089


